django_advance_reservation/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('application/', views.application, name="application"),    # 신청 페이지
    path('<int:pk>/update/', views.update, name="update"),          # 신청 정보 수정
    path('delete/', views.delete, name="delete"),          # 신청 정보 삭제
    path('<int:pk>/', views.detail, name="detail"),                 # 신청 정보 확인
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reservation/', include('reservation.urls')),
]

django_advance_reservation/django_advance_reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from reservation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
]

django_advance_reservation/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser # AbstractUser를 가져옴

class User(AbstractUser): # User 모델에 추가할 필드를 넣기 위해 AbstractUser 상속받음
    phone_number = models.CharField(max_length=11)
    korean_name = models.CharField(max_length=30,blank=True)
    email_address = models.EmailField()
    sweetpotato_size = models.CharField(max_length=30, blank=True)
    sweetpotato_num = models.IntegerField(default=1)
    address = models.CharField(max_length=500)
    sweetpotato_type = models.CharField(max_length=40,blank=True)

django_advance_reservation/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm # 기본 제공하는 modelForm을 사용하기 위해
from django import forms
from .models import User		# 커스터마이징한 User 모델을 불러옴
from django.contrib.auth.forms import UserChangeForm  # User 정보를 수정하기 위해
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model		# User 정보를 수정할 때 정보를 가져오기 위해

class ApplicationForm(UserCreationForm):		# 상속받아 사용할 클래스 선언
    def __init__(self, *args, **kwargs):	# init을 통해 존재하던 필드의 정보를 수정
        super().__init__(*args, **kwargs)
        class_update_fields = ['password1', 'password2']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:					 # Meta 클래스를 통해 새로 추가한 필드의 attrs에서 form-control 추가
        model = User			 # Bootstrap을 사용하기 위해서 추가했음
        fields = (
            'username',
            'korean_name',
            'email_address',
            'sweetpotato_size',
            'sweetpotato_num',
            'address',
            'phone_number',
            'sweetpotato_type',
        )
        SIZE_CHOICES = (
            ('대','대'),
            ('중','중'),
            ('중','소'),
        )
        SWEETPOTATO_TYPE = (
            ('호박고구마', '호박고구마'),
            ('밤고구마','밤고구마')
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'korean_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'email_address': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'sweetpotato_size': forms.Select(
                choices=SIZE_CHOICES,
                attrs={
                    'class': 'form-control',
                }
            ),
            'sweetpotato_num': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'phone_number': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'sweetpotato_type': forms.Select(
                choices=SWEETPOTATO_TYPE,
                attrs={
                    'class':'form-control'
                }
            )
        }
class myAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(myAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
        self.fields['password'].widget = forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ) 
    class Meta:
        model = User
        fields = ['username','password']
    



class ApplicationChangeForm(UserChangeForm):		# User 정보를 update하기 위하여 
    class Meta:
        model = get_user_model()
        fields = ['username', 'email_address','korean_name','address', 'sweetpotato_num', 'sweetpotato_size', 'phone_number', 'sweetpotato_type']
        SIZE_CHOICES = (
            ('대','대'),
            ('중','중'),
            ('중','소'),
        )
        SWEETPOTATO_TYPE = (
            ('호박고구마', '호박고구마'),
            ('밤고구마','밤고구마')
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'korean_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'email_address': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'sweetpotato_size': forms.Select(
                choices=SIZE_CHOICES,
                attrs={
                    'class': 'form-control',
                }
            ),
            'sweetpotato_num': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'phone_number': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'sweetpotato_type': forms.Select(
                choices=SWEETPOTATO_TYPE,
                attrs={
                    'class':'form-control'
                }
            )
        }

django_advance_reservation/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ApplicationForm
from .forms import ApplicationChangeForm
from .forms import myAuthenticationForm
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.mail import send_mail

# Create your views here.

def application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reservation:index')
    else:
        form = ApplicationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/application.html', context)
    
def detail(request, pk):
    application_list = get_user_model()
    form = get_object_or_404(application_list, pk=pk)
    context = {
        'form': form
    }
    return render(request, 'accounts/detail.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect("reservation:index")
    if request.method=="POST":
        form = myAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("reservation:index")
    else:
        form = myAuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect("reservation:index")


def update(request, pk):
    if request.method=="POST":
        form = ApplicationChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('reservation:index')
    else:
        form = ApplicationChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def delete(request):
    request.user.delete()
    return redirect('reservation:index')

django_advance_reservation/accounts/templates/accounts/application.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<p class="text-danger">{{ form.errors }}</p>
<div class="container" style="opacity: 1; background-color: white; height: auto;">
  <form action="{% url 'accounts:application' %}" method="POST">
    {% csrf_token %}
    <div class="form-row mb-4">
      <div class="col-12">
        <label >아이디</label>
        {{ form.username }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-6">
        <label>비밀번호</label>
        {{ form.password1 }}
      </div>
      <div class="col-6">
        <label>비밀번호 확인</label>
        {{ form.password2 }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>이름</label>
        {{ form.korean_name }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>핸드폰 번호</label>
        {{ form.phone_number }}
      </div>
    </div>  
    <div class="form-row mb-4">
      <div class="col-12">
        <label>주소</label>
        {{ form.address }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>email 주소</label>
        {{ form.email_address }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-6">
        <label>고구마 종류</label>
        {{ form.sweetpotato_type }}
      </div>
      <!-- <div class="col-4">
        <label>고구마 사이즈</label>
        {{ form.sweetpotato_size }}
      </div> -->
      <div class="col-6">
        <label>신청 수량(1box=10Kg)</label>
        {{ form.sweetpotato_num }}
      </div>
    </div>
    <button class="btn btn-info">제출</button>
  </form>
</div>

{% endblock %}

django_advance_reservation/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <form class="mt-5" action="{% url 'accounts:delete'  %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="form-row mb-4">
                <div class="col-12">
                  <label>이름</label>
                  <div class="form-control">{{ form.korean_name }}</div>
                </div>
              </div>
              <div class="form-row mb-4">
                <div class="col-12">
                  <label>핸드폰 번호</label>
                  <div class="form-control">{{ form.phone_number }}</div>
                </div>
              </div>  
              <div class="form-row mb-4">
                <div class="col-12">
                  <label>주소</label>
                  <div class="form-control">{{ form.address }}</div>
                </div>
              </div>
              <div class="form-row mb-4">
                <div class="col-12">
                  <label>email 주소</label>
                  <div class="form-control">{{ form.email_address }}</div>
                </div>
              </div>
              <div class="form-row mb-4">
                <div class="col-6">
                  <label>고구마 종류</label>
                  <div class="form-control">{{ form.sweetpotato_type }}</div>
                </div>
                <!-- <div class="col-4">
                  <label>고구마 사이즈</label>
                  <div class="form-control">{{ form.sweetpotato_size }}</div>
                </div> -->
                <div class="col-6">
                  <label>신청 수량(1box=10Kg)</label>
                  <div class="form-control">{{ form.sweetpotato_num }}</div>
                </div>
              </div>
        </div>
        {% if request.user == form %}
        <a href="{% url 'accounts:update' form.pk %}" class="btn btn-primary">신청 정보 수정</a>
        <button class="btn btn-secondary">신청 내용 삭제</button>
    </form>
    {% endif %}
{% endblock %}

django_advance_reservation/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="align-items-center">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-row mt-4 mb-4">
      <div class="col-12">
        <label for="id_username" class="mb-4">아이디</label>
      </div>
      <div class="col-12">{{ form.username }}</div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label for="id_password" class="mb-4">비밀번호</label>
      </div>
      <div class="col-12">{{ form.password }}</div>
    </div>
    <div>
      <button class="btn btn-primary">로그인</button>
      <a class="btn btn-primary float-right" href="{% url 'accounts:application' %}">회원가입</a>
  </div>
  </form>
</div>
{% endblock %}

django_advance_reservation/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <h1 class="text-center mt-5">신청 정보 수정</h1>
  <p class="text-danger">{{ form.errors }}</p>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-row mb-4">
      <div class="col-12">
        <label>아이디</label>
        {{ form.username }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>이름</label>
        {{ form.korean_name }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>핸드폰 번호</label>
        {{ form.phone_number }}
      </div>
    </div>  
    <div class="form-row mb-4">
      <div class="col-12">
        <label>주소</label>
        {{ form.address }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-12">
        <label>email 주소</label>
        {{ form.email_address }}
      </div>
    </div>
    <div class="form-row mb-4">
      <div class="col-6">
        <label>고구마 종류</label>
        {{ form.sweetpotato_type }}
      </div>
      <!-- <div class="col-4">
        <label>고구마 사이즈</label>
        {{ form.sweetpotato_size }}
      </div> -->
      <div class="col-6">
        <label>신청 수량(1box=10Kg)</label>
        {{ form.sweetpotato_num }}
      </div>
    </div>
    <button class="btn btn-info">수정</button>
  </form>

{% endblock %}