django_advance_reservation/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('application/', views.application, name="application"),    # 신청 페이지
    path('<int:pk>/update/', views.update, name="update"),          # 신청 정보 수정
    path('delete/', views.delete, name="delete"),          # 신청 정보 삭제
    path('<int:pk>/', views.detail, name="detail"),                 # 신청 정보 확인
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reservation/', include('reservation.urls')),
]

django_advance_reservation/django_advance_reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from reservation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
]

django_advance_reservation/reservation/urls.py
from django.urls import path, include
from . import views

app_name = "reservation"

urlpatterns = [
    path('', views.index, name="index"),            # 메인 페이지
    path('board/', views.board, name="board"),      # 고구마 정보를 보여주기 위해
    path('notice/', views.notice, name="notice"),
    path('QandA/', views.QandA_list, name="QandA_list"),
    path('QandA_create/', views.QandA_create, name='QandA_create'),
    path('QandA/<int:qanda_pk>/', views.QandA_detail, name='QandA_detail'),
    path('QandA/<int:qanda_pk>/reply/',views.reply_create, name='reply_create'),
    path('QandA/<int:qanda_pk>/reply/<int:reply_pk>/delete/', views.reply_delete, name='reply_delete'),
    path('QandA/<int:qanda_pk>/update/', views.QandA_update, name='QandA_update'),
    path('QandA/<int:qanda_pk>/delete/', views.QandA_delete, name='QandA_delete'),
]

django_advance_reservation/reservation/models.py
from django.db import models
from django.conf import settings

class QandA(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()

class Reply(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    QandA = models.ForeignKey(QandA, on_delete=models.CASCADE)
    content = models.TextField()

    

django_advance_reservation/reservation/forms.py
from django import forms
from .models import Reply, QandA

class QandAForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':'form-control'
            }
        )
    )
    class Meta:
        model = QandA
        fields =['title', 'content']

class ReplyForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control'
            }
        )
    )
    class Meta:
        model = Reply
        fields = ['content']
        

django_advance_reservation/reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from accounts.models import User
from django.contrib import messages
from .models import Reply, QandA
from .forms import ReplyForm, QandAForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator

# Create your views here.

def index(request):     # 메인 페이지에 가장 먼저 보여줄 것들
    users = User.objects.all()
    context= {
        'users':users
    }
    return render(request, 'reservation/index.html', context)

def board(request):     # 필요한 사진과 정보를 올려둘 board
    return render(request, 'reservation/board.html')

def notice(request):    # 공지사항을 위해
    return render(request, 'reservation/notice.html')

def QandA_list(request):
    QandAs = QandA.objects.order_by('-pk')    
    paginator = Paginator(QandAs, 4) #한 페이지 당 몇개 씩 보여줄 지 지정
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    reviews_all = get_list_or_404(QandA)
    total_count = len(reviews_all)
    total_page = total_count//4 + 1
    page_range = range(1,total_page+1)
    context = {
        'QandAs' : QandAs,
        'page_obj': page_obj,
        'page_range': page_range,
    }
    return render(request, 'reservation/QandA.html', context)

@login_required
def QandA_create(request):
    if request.method == 'POST':
        form = QandAForm(request.POST)
        if form.is_valid():
            QandA = form.save(commit=False)
            QandA.user = request.user
            QandA.save()
            return redirect('reservation:QandA_list')
    else:
        form = QandAForm()
    context = {
        'form' : form
    }
    return render(request, 'reservation/QandA_create.html', context)

@login_required    
def QandA_detail(request, qanda_pk):
    qanda = get_object_or_404(QandA, pk=qanda_pk)

    if qanda.user == request.user:
        form = ReplyForm()
        context = {
            'qanda':qanda,
            'form':form
        }
        return render(request, 'reservation/QandA_detail.html', context)
    else:
        messages.warning(request, '본인 글만 확인 가능합니다.')
        return redirect('reservation:QandA_list')

@login_required
def QandA_update(request, qanda_pk):
    qanda = get_object_or_404(QandA, pk=qanda_pk)
    if request.method == 'POST':
        form = QandAForm(request.POST, instance=qanda)
        if form.is_valid():
            qanda = form.save(commit=False)
            qanda.user = request.user
            qanda.save()
            return redirect('reservation:QandA_detail', qanda.pk)
    else:
        form = QandAForm(instance=qanda)
    context = {
        'form': form
    }
    return render(request, 'reservation/QandA_create.html', context)

@login_required
def QandA_delete(request, qanda_pk):
    qanda = get_object_or_404(QandA, pk=qanda_pk)
    if request.user == qanda.user:
        qanda.delete()
    return redirect('reservation:QandA_list')

        

@require_POST
@login_required
def reply_create(request, qanda_pk):
    qanda = get_object_or_404(QandA, pk=qanda_pk)
    form = ReplyForm(request.POST)
    if form.is_valid():
        reply=form.save(commit=False)
        reply.user = request.user
        reply.QandA = qanda
        reply.save()
    return redirect('reservation:QandA_detail',qanda.pk)

@login_required
def reply_delete(request, reply_pk, qanda_pk):
    reply = Reply.objects.get(pk=reply_pk)
    reply.delete()
    return redirect('reservation:QandA_detail',qanda_pk)

django_advance_reservation/reservation/templates/reservation/QandA.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


  <h2 class="mt-4">Q&A</h2>
  <hr>
  {% for qanda in page_obj %}
    <div class="card mb-3 mt-4 border-dark" onclick="location.href='/reservation/QandA/{{ qanda.pk }}/'" style="cursor:pointer">
      <div class="card-header">
          {{ qanda.user }}
      </div>
      <div class="card-body">
          <p class="card-text">{{ qanda.title }} </p>
      </div>
    </div>
  {% endfor %}
  <!-- paginator -->
  <div class="row justify-content-between">
    <div class="col-2">
        <a href="{% url 'reservation:QandA_create' %}" class="btn btn-info">글쓰기</a>
    </div>
    <nav aria-label="Page navigation col-12">
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% for page in page_range %}
            {% if page_obj.number == page %}
                <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}<span class="sr-only">(current)</span></a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        {% endif %}
        </ul>
    </nav>
  </div>
  
{% endblock %}

django_advance_reservation/reservation/templates/reservation/QandA_create.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% if request.resolver_match.url_name == 'QandA_create' %}
<h2>글 쓰기</h2>
{% else %}
<h2>글 수정</h2>
{% endif %}
<hr>
<form action="" method="POST">
  {% csrf_token %}
  <div class="form-row">
    <div class="col-12">
      <label for="id_title">제목</label>
      <div>{{ form.title }}</div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-12">
      <label for="id_content">내용</label>
      <div>{{ form.content }}</div>
    </div>
  </div>
  {% if request.resolver_match.url_name == 'QandA_create' %}
  <button class='btn btn-primary mt-3'>작성</button>
  {% else %}
  <button class='btn btn-primary mt-3'>수정</button>
  {% endif %}
  <a href="{% url 'reservation:QandA_list' %}" class="btn btn-secondary float-right mt-3">BACK</a>
</form>
{% endblock %}

django_advance_reservation/reservation/templates/reservation/QandA_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <h2 class="mt-4">질문</h2>
    <hr>
    <div class="form-group">
        <div class="form-row">
            <div class="col-2">
              <label for="id_username">작성자</label>
              <div class="form-control">{{ qanda.user }}</div>
            </div>
            <div class="col-10">
                <label for="id_username">제목</label>
                <div class="form-control">{{ qanda.title }}</div>
              </div>
        </div>
      
        <div class="form-row">
            <div class="col-12">
              <label for="id_username">내용</label>
              <div class="form-control"  style="height: auto;">{{ qanda.content}}</div>
            </div>
        </div>
    </div>
    <a href="{% url 'reservation:QandA_list' %}" class="btn btn-secondary">BACK</a>
    <a href="{% url 'reservation:QandA_update' qanda.pk %}" class="btn btn-primary">수정</a>
    <a href="{% url 'reservation:QandA_delete' qanda.pk %}" class="btn btn-danger">삭제</a>
    <hr>
    <h4>댓글</h4>
    <div class="form-group">
    {% for reply in qanda.reply_set.all %}
        <div class="form-row">
            <div class="form-control col-1"> {{ reply.user }}</div>
            <div class="form-control col-10 "> {{ reply.content }}</div>
            <a href="{% url 'reservation:reply_delete' qanda.pk reply.pk %}" class="btn btn-danger ml-auto border-light col-0.5">삭제</a>
        </div>
    {% endfor %}
    </div>
    <hr>
    <form action="{% url 'reservation:reply_create' qanda.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-11">{{ form.content }}</div>
            <button class="btn btn-info col-1">작성</button>
        </div>
    </form>
    <hr>


{% endblock %}

django_advance_reservation/reservation/templates/reservation/board.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div>board</div>
  

{% endblock %}

django_advance_reservation/reservation/templates/reservation/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


{% endblock %}

django_advance_reservation/reservation/templates/reservation/notice.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div>notice</div>
  

{% endblock %}