django_advance_reservation/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('application/', views.application, name="application"),    # 신청 페이지
    path('<int:pk>/update/', views.update, name="update"),          # 신청 정보 수정
    path('delete/', views.delete, name="delete"),          # 신청 정보 삭제
    path('<int:pk>/', views.detail, name="detail"),                 # 신청 정보 확인
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reservation/', include('reservation.urls')),
]

django_advance_reservation/django_advance_reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from reservation import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index),
]

django_advance_reservation/reservation/urls.py
from django.urls import path, include
from . import views

app_name = "reservation"

urlpatterns = [
    path('', views.index, name="index"),            # 메인 페이지
    path('board/', views.board, name="board"),      # 고구마 정보를 보여주기 위해
    path('notice/', views.notice, name="notice"),
    path('QandA/', views.QandA_list, name="QandA_list"),
    path('QandA_create/', views.QandA_create, name='QandA_create'),
    path('QandA/<int:qanda_pk>/', views.QandA_detail, name='QandA_detail'),
    path('QandA/<int:qanda_pk>/reply/',views.reply_create, name='reply_create'),
    path('QandA/<int:qanda_pk>/reply/<int:reply_pk>/delete/', views.reply_delete, name='reply_delete'),
    path('QandA/<int:qanda_pk>/update/', views.QandA_update, name='QandA_update'),
    path('QandA/<int:qanda_pk>/delete/', views.QandA_delete, name='QandA_delete'),
]

django_advance_reservation/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>고구마 사전예약</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'reservation:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if request.resolver_match.url_name == 'board' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %}
          <a class="nav-link" href="{% url 'reservation:board' %}">고구마 정보</a>
        </li>
        {% if user.is_authenticated %}
        {% else %}
        {% if request.resolver_match.url_name == 'application' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %}
          <a class="nav-link" href="{% url 'accounts:application' %}">신청하기</a>
        </li>
        {% endif %}
        {% if request.resolver_match.url_name == 'detail' or request.resolver_match.url_name == 'login' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %}
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:detail' user.pk %}">신청확인</a>
          {% else %}
          <a class="nav-link" href="{% url 'accounts:login' %}">신청확인</a>
          {% endif %}
        </li>
        {% if request.resolver_match.url_name == 'notice' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %}  
          <a class="nav-link" href="{% url 'reservation:notice' %}">안내사항</a>
        </li>
        {% if request.resolver_match.url_name == 'QandA_list' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %} 
          <a class="nav-link" href="{% url 'reservation:QandA_list' %}">Q&A</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
        {% else %}
        {% if request.resolver_match.url_name == 'login' %}
        <li class="nav-item active">
        {% else %}
        <li class="nav-item">
        {% endif %}
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        {% endif %}
    </div>
  </nav>

  <div>
    <!-- <img src="{% static 'images/고구마밭_1.jpg' %}" class="img-fluid"> -->
    <div class="container card-img-overlay mt-5">
      {% block body %}
      {% endblock %}
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-bottom justify-content-center">Designed by 구동엽</nav>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>